### ISSUE TITLE
App Crash On Android 10 (Model - Mi A2)

### ISSUE THREAD

**Issue by nileshsmarti** [inovait/neatle#56]
I am getting this error from Android version 10. Please check this.
 More details :
 Brand: Xiaomi Model: Mi A2 Orientation: Portrait RAM free: 795.8 MB Disk free: 7.28 GB 
 Version: 10 Orientation: Portrait Rooted: No 

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=62; index=-95
       at si.inova.neatle.scan.ScanRecord.createFromBytes(ScanRecord.java:98)
       at si.inova.neatle.scan.ScanEvent.<init>(ScanEvent.java:43)
       at si.inova.neatle.scan.LolipopLEScanner$ScanCallbackHandler.onLeScan(LolipopLEScanner.java:98)
       at android.bluetooth.BluetoothAdapter$3.onScanResult(BluetoothAdapter.java:3020)
       at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:498)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by tomazs** [comment]
Seems like this breaks with a nearby device. 

Can you use a BLE app from the play store to capture the BLE payload for the nearby devices?
